spring:
  profiles:
    active: prod
  main:
    banner-mode: "off"
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

app:
  version: 1.0.0
  autor: Ramon
  batch:
    input-file: classpath:derechohambientes.txt
    chunk-size: 5